import { getChosung } from "@/lib/chosung-search";
import type { Recipe, RecipeCategory, RecipeSubCategory } from "@/database/recipe/recipe.type";
export type { Recipe, RecipeCategory, RecipeSubCategory } from "@/database/recipe/recipe.type";

const sampleTimestamp = "2026-07-21T00:00:00.000Z";

function createSampleRecipe(id: string, name: string, category: RecipeCategory, subCategory: RecipeSubCategory): Recipe {
	return {
		id,
		name,
		category,
		subCategory,
		chosung: getChosung(name).replace(/\s/g, ""),
		createdAt: sampleTimestamp,
		updatedAt: sampleTimestamp,
	};
}

export const beverageSubCategories: RecipeSubCategory[] = ["카페인", "디카페인", "논커피", "에이드/티", "플랫치노", "생과일", "시즌 음료"];
export const bakerySubCategories: RecipeSubCategory[] = ["베이글", "브레드", "케이크", "디저트"];
export const eventSubCategories: RecipeSubCategory[] = ["시즌", "세트", "페어링"];

export const sampleRecipes: Recipe[] = [
	createSampleRecipe("hot-americano", "HOT 아메리카노", "음료", "카페인"),
	createSampleRecipe("iced-americano", "ICED 아메리카노", "음료", "카페인"),
	createSampleRecipe("hot-cafe-latte", "HOT 카페라떼", "음료", "카페인"),
	createSampleRecipe("iced-cafe-latte", "ICED 카페라떼", "음료", "카페인"),
	createSampleRecipe("hot-cappuccino", "HOT 카푸치노", "음료", "카페인"),
	createSampleRecipe("iced-cappuccino", "ICED 카푸치노", "음료", "카페인"),
	createSampleRecipe("hot-condensed-milk-cafe-latte", "HOT 연유카페라떼", "음료", "카페인"),
	createSampleRecipe("iced-condensed-milk-cafe-latte", "ICED 연유카페라떼", "음료", "카페인"),
	createSampleRecipe("hot-vanilla-latte", "HOT 바닐라라떼", "음료", "카페인"),
	createSampleRecipe("iced-vanilla-latte", "ICED 바닐라라떼", "음료", "카페인"),
	createSampleRecipe("hot-caramel-macchiato", "HOT 카라멜마끼아또", "음료", "카페인"),
	createSampleRecipe("iced-caramel-macchiato", "ICED 카라멜마끼아또", "음료", "카페인"),
	createSampleRecipe("hot-cafe-mocha", "HOT 카페모카", "음료", "카페인"),
	createSampleRecipe("iced-cafe-mocha", "ICED 카페모카", "음료", "카페인"),
	createSampleRecipe("hot-white-chocolate-mocha", "HOT 화이트초콜릿모카", "음료", "카페인"),
	createSampleRecipe("iced-white-chocolate-mocha", "ICED 화이트초콜릿모카", "음료", "카페인"),
	createSampleRecipe("hot-hazelnut-americano", "HOT 헤이즐넛 아메리카노", "음료", "카페인"),
	createSampleRecipe("iced-hazelnut-americano", "ICED 헤이즐넛 아메리카노", "음료", "카페인"),
	createSampleRecipe("hot-signature-latte", "HOT 시그니처라떼", "음료", "카페인"),
	createSampleRecipe("iced-signature-latte", "ICED 시그니처라떼", "음료", "카페인"),
	createSampleRecipe("hot-mint-mocha", "HOT 민트모카", "음료", "카페인"),
	createSampleRecipe("iced-mint-mocha", "ICED 민트모카", "음료", "카페인"),
	createSampleRecipe("iced-honey-white-americano", "ICED 꿀화이트 아메리카노", "음료", "카페인"),
	createSampleRecipe("iced-nuts-cream-latte", "ICED 넛츠크림라떼", "음료", "카페인"),
	createSampleRecipe("hot-daldal-coffee", "HOT 달달커피", "음료", "카페인"),
	createSampleRecipe("iced-daldal-coffee", "ICED 달달커피", "음료", "카페인"),
	createSampleRecipe("hot-zero-sugar-daldal-coffee", "HOT 제로슈가 달달커피", "음료", "카페인"),
	createSampleRecipe("iced-zero-sugar-daldal-coffee", "ICED 제로슈가 달달커피", "음료", "카페인"),
	createSampleRecipe("affogato", "아포가토", "음료", "카페인"),
	createSampleRecipe("iced-cold-brew", "ICED 콜드브루", "음료", "카페인"),
	createSampleRecipe("iced-cold-brew-latte", "ICED 콜드브루라떼", "음료", "카페인"),
	createSampleRecipe("iced-brown-sugar-cold-brew", "ICED 흑당콜드브루", "음료", "카페인"),
	createSampleRecipe("iced-condensed-milk-cold-brew", "ICED 연유콜드브루", "음료", "카페인"),
	createSampleRecipe("hot-matcha-latte", "HOT 말차라떼", "음료", "논커피"),
	createSampleRecipe("iced-matcha-latte", "ICED 말차라떼", "음료", "논커피"),
	createSampleRecipe("hot-toffee-nut-latte", "HOT 토피넛라떼", "음료", "논커피"),
	createSampleRecipe("iced-toffee-nut-latte", "ICED 토피넛라떼", "음료", "논커피"),
	createSampleRecipe("hot-chocolate", "HOT 초콜릿", "음료", "논커피"),
	createSampleRecipe("iced-chocolate", "ICED 초콜릿", "음료", "논커피"),
	createSampleRecipe("hot-mint-chocolate", "HOT 민트초콜릿", "음료", "논커피"),
	createSampleRecipe("iced-mint-chocolate", "ICED 민트초콜릿", "음료", "논커피"),
	createSampleRecipe("hot-white-chocolate", "HOT 화이트초콜릿", "음료", "논커피"),
	createSampleRecipe("iced-white-chocolate", "ICED 화이트초콜릿", "음료", "논커피"),
	createSampleRecipe("iced-strawberry-chocolate-latte", "ICED 딸기초코라떼", "음료", "논커피"),
	createSampleRecipe("iced-matcha-chocolate-latte", "ICED 말차초코라떼", "음료", "논커피"),
	createSampleRecipe("hot-sweet-potato-latte", "HOT 고구마라떼", "음료", "논커피"),
	createSampleRecipe("iced-sweet-potato-latte", "ICED 고구마라떼", "음료", "논커피"),
	createSampleRecipe("iced-brown-sugar-latte", "ICED 흑당라떼", "음료", "논커피"),
	createSampleRecipe("iced-dalgona-latte", "ICED 달고나라떼", "음료", "논커피"),
	createSampleRecipe("iced-strawberry-full-latte", "ICED 딸기듬뿍라떼", "음료", "논커피"),
	createSampleRecipe("hot-misutgaru-latte", "HOT 미숫가루라떼", "음료", "논커피"),
	createSampleRecipe("iced-misutgaru-latte", "ICED 미숫가루라떼", "음료", "논커피"),
	createSampleRecipe("iced-bubble-brown-sugar-latte", "ICED 버블흑당라떼", "음료", "논커피"),
	createSampleRecipe("iced-grapefruit-pomelo-ade", "ICED 자몽포멜로에이드", "음료", "에이드/티"),
	createSampleRecipe("iced-tangerine-lemon-ade", "ICED 감귤레몬에이드", "음료", "에이드/티"),
	createSampleRecipe("iced-honey-peach-ade", "ICED 꿀복숭아에이드", "음료", "에이드/티"),
	createSampleRecipe("iced-muscat-mojito-ade", "ICED 머스캣모히또 에이드", "음료", "에이드/티"),
	createSampleRecipe("iced-sangria-ade", "ICED 상그리아에이드", "음료", "에이드/티"),
	createSampleRecipe("iced-apple-carrot-cleanse-juice", "ICED 사과당근 클렌즈주스", "음료", "에이드/티"),
	createSampleRecipe("iced-kiwi-kale-celery-cleanse-juice", "ICED 키위케일샐러리 클렌즈주스", "음료", "에이드/티"),
	createSampleRecipe("hot-earl-grey", "HOT 얼그레이", "음료", "에이드/티"),
	createSampleRecipe("hot-chamomile", "HOT 캐모마일", "음료", "에이드/티"),
	createSampleRecipe("hot-peppermint", "HOT 페퍼민트", "음료", "에이드/티"),
	createSampleRecipe("hot-rooibos", "HOT 루이보스", "음료", "에이드/티"),
	createSampleRecipe("hot-hibiscus", "HOT 히비스커스", "음료", "에이드/티"),
	createSampleRecipe("iced-earl-grey", "ICED 얼그레이", "음료", "에이드/티"),
	createSampleRecipe("iced-chamomile", "ICED 캐모마일", "음료", "에이드/티"),
	createSampleRecipe("iced-peppermint", "ICED 페퍼민트", "음료", "에이드/티"),
	createSampleRecipe("iced-rooibos", "ICED 루이보스", "음료", "에이드/티"),
	createSampleRecipe("iced-hibiscus", "ICED 히비스커스", "음료", "에이드/티"),
	createSampleRecipe("hot-yuja-tea", "HOT 유자차", "음료", "에이드/티"),
	createSampleRecipe("hot-grapefruit-tea", "HOT 자몽차", "음료", "에이드/티"),
	createSampleRecipe("hot-lemon-tea", "HOT 레몬차", "음료", "에이드/티"),
	createSampleRecipe("hot-pear-quince-tea", "HOT 배모과차", "음료", "에이드/티"),
	createSampleRecipe("hot-ginger-tea", "HOT 생강차", "음료", "에이드/티"),
	createSampleRecipe("iced-yuja-tea", "ICED 유자차", "음료", "에이드/티"),
	createSampleRecipe("iced-grapefruit-tea", "ICED 자몽차", "음료", "에이드/티"),
	createSampleRecipe("iced-lemon-tea", "ICED 레몬차", "음료", "에이드/티"),
	createSampleRecipe("iced-pear-quince-tea", "ICED 배모과차", "음료", "에이드/티"),
	createSampleRecipe("iced-ginger-tea", "ICED 생강차", "음료", "에이드/티"),
	createSampleRecipe("iced-peach-iced-tea", "ICED 복숭아 아이스티", "음료", "에이드/티"),
	createSampleRecipe("iced-lemon-iced-tea", "ICED 레몬 아이스티", "음료", "에이드/티"),
	createSampleRecipe("iced-ashotchu-peach", "ICED 아샷추(복숭아)", "음료", "에이드/티"),
	createSampleRecipe("iced-amangchu-peach", "ICED 아망추(복숭아)", "음료", "에이드/티"),
	createSampleRecipe("iced-zero-sugar-peach-iced-tea", "ICED 아이스티(제로슈가 복숭아)", "음료", "에이드/티"),
	createSampleRecipe("iced-zero-sugar-ashotchu-peach", "ICED 아샷추(제로슈가 복숭아)", "음료", "에이드/티"),
	createSampleRecipe("hot-royal-milk-tea", "HOT 로열밀크티", "음료", "에이드/티"),
	createSampleRecipe("iced-royal-milk-tea", "ICED 로열밀크티", "음료", "에이드/티"),
	createSampleRecipe("hot-ssanghwa-tea", "HOT 쌍화차", "음료", "에이드/티"),
	createSampleRecipe("iced-ssanghwa-tea", "ICED 쌍화차", "음료", "에이드/티"),
	createSampleRecipe("hot-bokbunja-vin-chaud", "HOT 복분자뱅쇼", "음료", "에이드/티"),
	createSampleRecipe("iced-bokbunja-vin-chaud", "ICED 복분자뱅쇼", "음료", "에이드/티"),
	createSampleRecipe("iced-sikhye", "ICED 살얼음식혜", "음료", "에이드/티"),
	createSampleRecipe("iced-strawberry-juice", "ICED 딸기주스", "음료", "생과일"),
	createSampleRecipe("iced-mango-juice", "ICED 망고주스", "음료", "생과일"),
	createSampleRecipe("iced-blueberry-juice", "ICED 블루베리주스", "음료", "생과일"),
	createSampleRecipe("iced-strawberry-banana-juice", "ICED 딸기바나나주스", "음료", "생과일"),
	createSampleRecipe("iced-mango-banana-juice", "ICED 망고바나나주스", "음료", "생과일"),
	createSampleRecipe("iced-blueberry-banana-juice", "ICED 블루베리바나나주스", "음료", "생과일"),
	createSampleRecipe("iced-milk-shake", "ICED 밀크쉐이크", "음료", "생과일"),
	createSampleRecipe("iced-strawberry-shake", "ICED 딸기쉐이크", "음료", "생과일"),
	createSampleRecipe("iced-choco-cookie-shake", "ICED 초코쿠키쉐이크", "음료", "생과일"),
	createSampleRecipe("iced-espresso-shake", "ICED 에스프레소쉐이크", "음료", "생과일"),
	createSampleRecipe("iced-matcha-choco-shake", "ICED 말차초코쉐이크", "음료", "생과일"),
	createSampleRecipe("iced-mango-flatccino", "ICED 망고플랫치노", "음료", "플랫치노"),
	createSampleRecipe("iced-honey-peach-flatccino", "ICED 꿀복숭아플랫치노", "음료", "플랫치노"),
	createSampleRecipe("iced-yuja-grapefruit-flatccino", "ICED 유자몽플랫치노", "음료", "플랫치노"),
	createSampleRecipe("iced-toffee-nut-flatccino", "ICED 토피넛플랫치노", "음료", "플랫치노"),
	createSampleRecipe("iced-plain-yogurt-flatccino", "ICED 플레인요거트 플랫치노", "음료", "플랫치노"),
	createSampleRecipe("iced-strawberry-yogurt-flatccino", "ICED 딸기요거트 플랫치노", "음료", "플랫치노"),
	createSampleRecipe("iced-blueberry-yogurt-flatccino", "ICED 블루베리요거트 플랫치노", "음료", "플랫치노"),
	createSampleRecipe("iced-honey-peach-yogurt-flatccino", "ICED 꿀복숭아요거트 플랫치노", "음료", "플랫치노"),
	createSampleRecipe("iced-chocolate-chip-flatccino", "ICED 초콜릿칩플랫치노", "음료", "플랫치노"),
	createSampleRecipe("iced-mint-chocolate-chip-flatccino", "ICED 민트초콜릿칩 플랫치노", "음료", "플랫치노"),
	createSampleRecipe("plain-bagel", "플레인 베이글", "베이커리", "베이글"),
	createSampleRecipe("honey-bread", "허니 브레드", "베이커리", "브레드"),
	createSampleRecipe("honey-caramel-bread", "허니 카라멜 브레드", "베이커리", "브레드"),
	createSampleRecipe("croissant", "크루아상", "베이커리", "브레드"),
	createSampleRecipe("basque-cheesecake", "바스크치즈케이크", "베이커리", "케이크"),
	createSampleRecipe("spoon-up-tiramisu", "떠먹는 티라미수", "베이커리", "케이크"),
	createSampleRecipe("butter-pancake", "버터 팬케이크", "베이커리", "디저트"),
	createSampleRecipe("souffle-cheesecake", "수플레 치즈 케이크", "베이커리", "케이크"),
	createSampleRecipe("chocolate-tiramisu-cake", "초코 티라미수 케이크", "베이커리", "케이크"),
	createSampleRecipe("churros", "쌍쌍 츄로스", "베이커리", "디저트"),
	createSampleRecipe("summer-watermelon-event", "여름 수박 프로모션", "이벤트", "시즌"),
	createSampleRecipe("morning-set-event", "모닝 세트 이벤트", "이벤트", "세트"),
	createSampleRecipe("bakery-pairing-event", "베이커리 페어링 이벤트", "이벤트", "페어링"),
];
